services:
  mail:
    container_name: supabase-mail
    image: inbucket/inbucket:3.0.3
    networks:
      - supastar
    ports:
      - '2500:2500' # SMTP
      - '9000:9000' # web interface
      - '1100:1100' # POP3
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:9000/ping',
        ]
      timeout: 5s
      interval: 10s
      retries: 3
