services:
  studio:
    build:
      context: ..
      dockerfile: apps/studio/Dockerfile
      target: dev
    ports:
      - 8082:8082

  auth:
    environment:
      - GOTRUE_SMTP_USER=
      - GOTRUE_SMTP_PASS=
  meta:
    ports:
      - 5555:8080
  db:
    restart: 'no'
    volumes:
      # Always use a fresh database when developing
      - /var/lib/postgresql/data
      # Seed data should be inserted last (alphabetical order)
      - ./dev/data.sql:/docker-entrypoint-initdb.d/seed.sql
  storage:
    volumes:
      - /var/lib/storage
